// <auto-generated />
namespace TuHobbyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProductPlatformTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductPlatformTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202107061713022_ProductPlatformTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
